apiVersion: v1
kind: Service
metadata:
  name: split-log-output-svc
spec:
  type: ClusterIP
  selector:
    app: split-log-output
  ports:
    - name: fetch
      port: 2345
      protocol: TCP
      targetPort: 3000
    - name: write
      port: 2346
      protocol: TCP
      targetPort: 3001
