apiVersion: apps/v1
kind: Deployment
metadata:
  name: shared-ping-log-deployment
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shared-ping-log
  template:
    metadata:
      labels:
        app: shared-ping-log
    spec:
      volumes:
        - name: shared-ping-log-pvc
          persistentVolumeClaim:
            claimName: shared-ping-log-claim
        - name: shared-ping-log-config
          configMap:
            name: shared-ping-log-config-map
      containers:
        - name: ping-pong
          image: javiercoronadonarvaez/ping-pong:v1.2.1
          volumeMounts:
            - name: shared-ping-log-pvc
              mountPath: /usr/src/app/files
            - name: shared-ping-log-config
              mountPath: /usr/src/app/config
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          env:
            - name: PORT
              value: "3001"
        - name: log-output
          image: javiercoronadonarvaez/log-output:v1.2.1
          volumeMounts:
            - name: shared-ping-log-pvc
              mountPath: /usr/src/app/files
            - name: shared-ping-log-config
              mountPath: /usr/src/app/config
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          env:
            - name: PORT
              value: "3000"
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: shared-ping-log-config-map
                  key: MESSAGE
            - name: AXIOS_PING_PONG_BACKEND_URL
              valueFrom:
                configMapKeyRef:
                  name: shared-ping-log-config-map
                  key: AXIOS_PING_PONG_BACKEND_URL
