apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-ping-log-claim
spec:
  storageClassName: shared-ping-log-pv-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
