apiVersion: v1
kind: Service
metadata:
  name: shared-ping-log-svc
spec:
  type: ClusterIP
  selector:
    app: shared-ping-log
  ports:
    - name: log-output
      port: 2345
      protocol: TCP
      targetPort: 3000
    - name: ping-pong
      port: 2346
      protocol: TCP
      targetPort: 3001
