apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong-deployment
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      initContainers:
        - name: wait-for-postgres
          image: postgres:18
          command:
            [
              'sh',
              '-c',
              'until pg_isready -h ping-pong-svc -U postgres; do sleep 2; done',
            ]
          env:
            - name: POSTGRES_USER
              value: postgres
        - name: migrate
          image: javiercoronadonarvaez/ping-pong:v2.0.1
          command: ['sh', '-c', 'npx prisma migrate deploy']
          env:
            - name: DATABASE_URL
              value: 'postgresql://postgres:postgres@ping-pong-svc:5432/postgres'
      containers:
        - name: ping-pong
          image: javiercoronadonarvaez/ping-pong:v2.0.1
          resources:
            requests:
              cpu: '100m'
              memory: '128Mi'
            limits:
              cpu: '500m'
              memory: '512Mi'
          env:
            - name: PORT
              value: '3001'
            - name: DATABASE_URL
              value: 'postgresql://postgres:postgres@ping-pong-svc:5432/postgres'
