apiVersion: v1
kind: Service
metadata:
  name: ping-pong-app-lb
  namespace: exercises
spec:
  type: LoadBalancer
  selector:
    app: ping-pong
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3001
