apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-app-config-map
  namespace: project
data:
  BACKEND_PORT: "3000"
  IMAGE_FILE_PATH: "/usr/src/app/files/image.jpg"
  PICSUM_API_URL: "https://picsum.photos/1200"
  FRONTEND_PORT: "3001"
  VITE_BACKEND_URL: "http://localhost:8081"
  DATABASE_URL: "postgresql://postgres:postgres@postgres-svc:5432/todo"
