apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ping-log-ingress
spec:
  rules:
    - http:
        paths:
          - path: /pingpong
            pathType: Prefix
            backend:
              service:
                name: ping-pong-app-svc
                port:
                  number: 3001
          - path: /ping
            pathType: Prefix
            backend:
              service:
                name: ping-pong-app-svc
                port:
                  number: 3001
