apiVersion: v1
kind: Service
metadata:
  name: ping-pong-app-svc
spec:
  type: ClusterIP
  selector:
    app: ping-pong
  ports:
    - port: 3001
      targetPort: 3001
      protocol: TCP
      name: http
